services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
        DEBUG: 1
        SECRET_KEY: someverysecretkey
    ports:
      - 5001:8000
